In [3]:
# Bài 1:
nums = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]

print("Các vị trí chẵn:", nums[::2])
print("Tuple:", tuple(nums))
print("Dict:", {i: nums[i] for i in range(len(nums))})
print("Set:", set(nums))
print("Số phần tử bị loại trùng:", len(nums) - len(set(nums)))

Các vị trí chẵn: [1, 3, 5, 7, 9]
Tuple: (1, 2, 3, 2, 5, 1, 7, 9, 9, 4)
Dict: {0: 1, 1: 2, 2: 3, 3: 2, 4: 5, 5: 1, 6: 7, 7: 9, 8: 9, 9: 4}
Set: {1, 2, 3, 4, 5, 7, 9}
Số phần tử bị loại trùng: 3


In [20]:
# Bài 2:
import json

with open("data.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()
    for i in range(len(lines)):
        print(f"Dòng {i + 1}", lines[i].strip())

with open("students.json", "r", encoding="utf-8") as file:
    data = json.load(file)
    for student in data["students"]:
        name = student["name"]
        age = student["age"]
        avg_score = sum(student["scores"]) / len(student["scores"])
        print(f"JSON đọc từ file: {data.setdefault('students')}")

Dòng 1 Chào các bạn
Dòng 2 Hello
Dòng 3 M thích chơi game k?
Dòng 4 Thấy dòng này không?
Dòng 5 Đừng có nhìn!
JSON đọc từ file: [{'name': 'An', 'age': 20, 'scores': [8, 9, 7]}]


In [46]:
# Bài 3:
import numpy as np

arr_3x4 = np.array([[0, 1, 2, 3],
                    [4, 5, 6, 7],
                    [8, 9, 10, 11]])

print("Hàng 2:", arr_3x4[1])
print("Cột 3:", arr_3x4[:, 2])
print("Submatrix:", arr_3x4[1:3, 1:3])
print("Dtype mới:", arr_3x4.astype(np.float64).dtype)

Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrix: [[ 5  6]
 [ 9 10]]
Dtype mới: float64


In [47]:
# Bài 4:
import pandas as pd

name = ['An','Bình','Châu','Dũng','Hà']
age = [20,21,22,20,23]
score = [7.5, 8.0, 6.5, 9.0, 8.5] 

series = pd.Series(score)

df = pd.DataFrame({'Name': name, 'Age': age, 'Score': score})

print(df.info())
print(df.describe())
print("Sinh viên >= 8 điểm:\n", df[df['Score'] >= 8.0])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    5 non-null      object 
 1   Age     5 non-null      int64  
 2   Score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
None
            Age     Score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000
Sinh viên >= 8 điểm:
    Name  Age  Score
1  Bình   21    8.0
3  Dũng   20    9.0
4    Hà   23    8.5


In [ ]:
# Bài 5:
import pandas as pd

# 1. Đọc file CSV
students = pd.read_csv("students.csv")
scores = pd.read_csv("scores.csv")

# 2. Merge theo cột id
merged_df = pd.merge(students, scores, on="id")

# 3. Tính min - max - mean theo từng sinh viên
report = merged_df.groupby(["id", "name"])["score"].agg(
    min_score="min",
    max_score="max",
    mean_score="mean"
).reset_index()

# 4. Lưu file report.csv
report.to_csv("report.csv", index=False)

print("=== Report ===")
print(report)

    

In [6]:
# Bài 6:
import numpy as np

a = [[1],[2],[3],[4]]
b = [[10,20,30,40,50]]

print("Kết quả a*b:\n", np.multiply(a, b))
print("\nsqrt:\n", np.sqrt(np.multiply(a, b)))
print("\nlog:\n", np.log(np.multiply(a, b)))
print("\nmin:", np.min(np.multiply(a, b)))
print("\nmax:", np.max(np.multiply(a, b)))
print("\nmean theo axis=1:\n", np.mean(np.multiply(a, b), axis=1))
print("\nstd:", np.std(np.multiply(a, b)))

Kết quả a*b:
 [[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]

sqrt:
 [[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]

log:
 [[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]

min: 10

max: 200

mean theo axis=1:
 [ 30.  60.  90. 120.]

std: 51.234753829797995


In [11]:
# Bài 7:
import pandas as pd
import numpy as np

# Tạo DataFrame
data = {
    "name": ["An", "Bình", "Châu", "Dũng"],
    "age": [20, np.nan, 22, 21],
    "score": [8.5, np.nan, 7.0, 9.0],
    "city": ["Hà Nội", "HCM", np.nan, "Hà Nội"]
}

df = pd.DataFrame(data)

print("=== Kiểm tra dữ liệu thiếu ===")
print(df.isna())

# --- B1: Điền dữ liệu thiếu ---
df.fillna(df["age"].mean(), inplace=True)
df.fillna(df["score"].median(), inplace=True)
df.fillna("Unknown", inplace=True)

# --- B2: Chuyển city sang category ---
df["city"] = df["city"].astype("category")

# --- B3: Tạo cột score_level bằng apply() ---
def classify(score):
    if score >= 8:
        return "Good"
    elif score >= 7:
        return "Average"
    else:
        return "Bad"

df["score_level"] = df["score"].apply(classify)

# --- B4: Chuẩn hóa tuổi bằng pipeline ---
age_mean = df["age"].mean()
age_std = df["age"].std()

df["age_normalized"] = (df["age"] - age_mean) / age_std

print("\n=== DataFrame sau xử lý ===")
print(df)

=== Kiểm tra dữ liệu thiếu ===
    name    age  score   city
0  False  False  False  False
1  False   True   True  False
2  False  False  False   True
3  False  False  False  False

=== DataFrame sau xử lý ===
   name   age  score    city score_level  age_normalized
0    An  20.0    8.5  Hà Nội        Good       -1.224745
1  Bình  21.0   21.0     HCM        Good        0.000000
2  Châu  22.0    7.0    21.0     Average        1.224745
3  Dũng  21.0    9.0  Hà Nội        Good        0.000000


In [12]:
# Bài 8:
from pathlib import Path
from datetime import datetime
import json
import pandas as pd

# Thư mục chứa file log JSON
log_dir = Path("logs")

# Lấy toàn bộ file .json trong thư mục
json_files = list(log_dir.glob("*.json"))

records = []

for file in json_files:
    # Lấy ngày từ tên file: ví dụ "log_2025-01-02.json"
    date_str = file.stem.split("_")[1]     # "2025-01-02"
    file_date = datetime.strptime(date_str, "%Y-%m-%d").date()

    # Đọc nội dung JSON
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Thêm thông tin vào danh sách
    records.append({
        "date": file_date,
        "user": data.get("user"),
        "action": data.get("action"),
        "duration": data.get("duration")
    })

# Đưa vào DataFrame
df = pd.DataFrame(records)

# Tính tổng duration theo ngày
daily_report = df.groupby("date")["duration"].sum().reset_index()

# Xuất file CSV
daily_report.to_csv("daily_report.csv", index=False)

print("=== DAILY REPORT ===")
print(daily_report)


=== DAILY REPORT ===
         date  duration
0  2025-01-01         5
1  2025-01-02         6
2  2025-01-03         7
