In [2]:

import numpy as np

In [25]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

arr1 = np.arange(1, 11)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# Bài 1:
print("shape1:", arr1.shape)
print("dtype1:", arr1.dtype)

print("shape2:", arr2.shape)
print("dtype2:", arr2.dtype)
print("dtype_float:", arr2.astype(float).dtype)

shape1: (10,)
dtype1: int64
shape2: (3, 3)
dtype2: int64
dtype_float: float64


In [19]:
# Bài 2:
print("first_elem =", np.min(arr1))
print("last_elem =", np.max(arr1))
print("middle_elem =", round(np.median(arr1)))
print("sliced_arr =", arr1[2:5])
print("row2 =", arr2[1, :])
print("col3 =", arr2[:, 2])

first_elem = 1
last_elem = 10
middle_elem = 6
sliced_arr = [3 4 5]
row2 = [4 5 6]
col3 = [3 6 9]


In [24]:
# Bài 3:
arr = [[88, 35, 62],

 [11, 98, 34],

 [64, 24, 48]]

print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Sum", np.sum(arr))
print("Mean:", np.mean(arr))
print("Std:", np.std(arr))
print()
print("SumOfColumn:", np.sum(arr, axis=0))
print("MeanOfColumn:", np.mean(arr, axis=0))
print()
print("SumOfRow:", np.sum(arr, axis=1))
print("MeanOfRow:", np.mean(arr, axis=1))

Min: 11
Max: 98
Sum 464
Mean: 51.55555555555556
Std: 27.38252123409754

SumOfColumn: [163 157 144]
MeanOfColumn: [54.33333333 52.33333333 48.        ]

SumOfRow: [185 143 136]
MeanOfRow: [61.66666667 47.66666667 45.33333333]


In [28]:
# Bài 4:
A = [[5, 6, 8],

 [7, 2, 4],

 [1, 6, 3]]

B = [10, 20, 30]

print("Kết quả phép cộng A + B:\n", np.add(arr1, arr2))
print("Kết quả phép trừ A - B:\n", np.subtract(arr1, arr2))

Kết quả phép cộng A + B:
 [[15 26 38]
 [17 22 34]
 [11 26 33]]
Kết quả phép trừ A - B:
 [[ -5 -14 -22]
 [ -3 -18 -26]
 [ -9 -14 -27]]


In [32]:
# Bài 5:
arr = [5,3,2,5,7,9,1,4,6,8,11,10,15,14,13,12,18,17,16,19,20]

arr_np = np.array(arr)

sq = arr_np ** 2        # bình phương
root = np.sqrt(arr_np)  # căn bậc hai

print(sq)
print(root)
print(np.add(arr_np, 2))
print(np.multiply(arr_np, 3))
print(np.sqrt(arr_np))

[ 25   9   4  25  49  81   1  16  36  64 121 100 225 196 169 144 324 289
 256 361 400]
[2.23606798 1.73205081 1.41421356 2.23606798 2.64575131 3.
 1.         2.         2.44948974 2.82842712 3.31662479 3.16227766
 3.87298335 3.74165739 3.60555128 3.46410162 4.24264069 4.12310563
 4.         4.35889894 4.47213595]
[ 7  5  4  7  9 11  3  6  8 10 13 12 17 16 15 14 20 19 18 21 22]
[15  9  6 15 21 27  3 12 18 24 33 30 45 42 39 36 54 51 48 57 60]
[2.23606798 1.73205081 1.41421356 2.23606798 2.64575131 3.
 1.         2.         2.44948974 2.82842712 3.31662479 3.16227766
 3.87298335 3.74165739 3.60555128 3.46410162 4.24264069 4.12310563
 4.         4.35889894 4.47213595]


In [ ]:
# Bài 6:
arr_4x4 = [[3, 7, 4, 5],

 [3, 5, 2, 4],

 [6, 3, 9, 7],

 [4, 8, 3, 5]]

print("Tổng theo cột(axis=0):", np.sum(arr_4d, axis=0))
print("Trung bình theo cột(axis=0):", np.mean(arr_4d, axis=0))
print("Độ lệch chuẩn theo cột(axis=0):", np.std(arr_4d, axis=0))

print("Tổng theo hàng(axis=1):", np.sum(arr_4d, axis=1))
print("Trung bình theo hàng(axis=1):", np.mean(arr_4d, axis=1))
print("Độ lệch chuẩn theo hàng(axis=1):", np.std(arr_4d, axis=1))

Tổng theo cột(axis=0): [16 23 18 21]
Trung bình theo cột(axis=0): [4.   5.75 4.5  5.25]
Độ lệch chuẩn theo cột(axis=0): [1.22474487 1.92028644 2.6925824  1.08972474]
Tổng theo hàng(axis=1): [19 14 25 20]
Trung bình theo hàng(axis=1): [4.75 3.5  6.25 5.  ]
Độ lệch chuẩn theo hàng(axis=1): [1.47901995 1.11803399 2.16506351 1.87082869]


In [11]:
# Bài 7:
import time

arr_5x5 = [[ 8, 12, 14,  6,  4],

 [18, 13,  2,  2, 12],

 [ 6, 18, 5, 10, 10],

 [ 9,  2,  4, 12, 12],

 [ 2, 3,  2, 17,  3]]

arr_1d = [10, 20, 30, 40, 50]

print("Kết quả phép cộng:\n", np.add(arr_5x5, arr_1d))
print("\nKết quả phép trừ:\n", np.subtract(arr_5x5, arr_1d))
print("\nKết quả căn bậc hai(ufunc):\n", np.sqrt(arr_5x5))
print("\nKết quả cộng 5 vào mảng(ufunc):\n", np.add(arr_5x5, 5))
print("\nThời gian thực thi vòng lặp thủ công:", time.time())


Kết quả phép cộng:
 [[18 32 44 46 54]
 [28 33 32 42 62]
 [16 38 35 50 60]
 [19 22 34 52 62]
 [12 23 32 57 53]]

Kết quả phép trừ:
 [[ -2  -8 -16 -34 -46]
 [  8  -7 -28 -38 -38]
 [ -4  -2 -25 -30 -40]
 [ -1 -18 -26 -28 -38]
 [ -8 -17 -28 -23 -47]]

Kết quả căn bậc hai(ufunc):
 [[2.82842712 3.46410162 3.74165739 2.44948974 2.        ]
 [4.24264069 3.60555128 1.41421356 1.41421356 3.46410162]
 [2.44948974 4.24264069 2.23606798 3.16227766 3.16227766]
 [3.         1.41421356 2.         3.46410162 3.46410162]
 [1.41421356 1.73205081 1.41421356 4.12310563 1.73205081]]

Kết quả cộng 5 vào mảng(ufunc):
 [[13 17 19 11  9]
 [23 18  7  7 17]
 [11 23 10 15 15]
 [14  7  9 17 17]
 [ 7  8  7 22  8]]

Thời gian thực thi vòng lặp thủ công: 1764039913.267122


In [12]:
# Bài 8:
arr_3x3 = [[5, 6, 8],

 [7, 2, 4],

 [1, 6, 3]]

print("Ma trận nghịch đảo:\n", np.linalg.inv(arr_3x3))
print("\nGía trị riêng của ma trận:\n", np.linalg.eigvals(arr_3x3))
print("\nVector riêng của ma trận:\n", np.linalg.eig(arr_3x3))

Ma trận nghịch đảo:
 [[-0.140625   0.234375   0.0625   ]
 [-0.1328125  0.0546875  0.28125  ]
 [ 0.3125    -0.1875    -0.25     ]]

Gía trị riêng của ma trận:
 [13.79098545+0.j         -1.89549273+2.38506447j -1.89549273-2.38506447j]

Vector riêng của ma trận:
 EigResult(eigenvalues=array([13.79098545+0.j        , -1.89549273+2.38506447j,
       -1.89549273-2.38506447j]), eigenvectors=array([[ 0.73224025+0.j        , -0.21033088-0.35792375j,
        -0.21033088+0.35792375j],
       [ 0.56414351+0.j        , -0.51519709+0.32773465j,
        -0.51519709-0.32773465j],
       [ 0.38153154+0.j        ,  0.6743986 +0.j        ,
         0.6743986 -0.j        ]]))
